### ISSUE TITLE
Unofficial roadmap

### ISSUE THREAD

**Issue by aleclarson** [ptmt/react-native-macos#230]
I'm going to use this issue to track which features I've worked on / plan to work (eventually). 
Others are welcome to do the same in their own reply to this issue.

- [x] Upgrade `<Text>` and `<TextInput>` to RN 0.54 (#227)
- [x] Add `RCTWindow` for improved input handling (#228)
- [x] Add support for React hooks (#225)
- [x] Create a library for native SVG support (#229)
- [ ] Support `onMouseEnter` and `onMouseLeave` events
- [ ] Support `pointerEvents` prop
- [ ] Add native `Worker` class ([→ branch](https://github.com/aleclarson/react-native-macos/tree/worker))

**Comment by eveningkid** [comment]
Thank you so much for doing this @aleclarson. 

It has been a year or so that I've wanted to start an app using `react-native-macos` and I feel that this project might eventually soon be ready-to-use thanks to your work!

Good luck for everything, really.

**Comment by pgavazzi** [comment]
Do we know if facebook is planning to release an official react-native-macos?

**Comment by aleclarson** [comment]
@pgavazzi They're most definitely not. See here: https://github.com/react-native-community/discussions-and-proposals/issues/4#issuecomment-447605070

**Comment by fungilation** [comment]
@aleclarson no need with Catalyst? Just add Mac as new target next to iPhone and iPad, if RN proper fixes any kinks with that in Xcode 11.

https://github.com/ptmt/react-native-macos/issues/244

**Comment by aleclarson** [comment]
Just pushed these to master:

- Reimplement the native `hitSlop` prop (6e9db010fbcd1a2901e3c91fb76d8f95dd871747)
- Fix `zIndex` prop being ignored (ab257a13b397f983fb865058a5b6435559c1f683)
- Respect `layer.transform` inside `hitTest` (1f1389653b7bdf3d4494f361a1d591fca7332f94)

**Comment by adamierymenko** [comment]
Just wanted to mention -- I hope this doesn't get abandoned because of Catalyst. Yes you can run iPad apps on Mac now, but so far the experience seems marginal. They do not look, feel, or behave anything like Mac native apps. The font rendering seems wonky too. Maybe these things will get fixed eventually but so far Catalyst apps feel non-native much like Electron apps.
